#x = int(input('De qual numero você quer saber a tabuada?'))
#b = (x*1)
#c = (x*2)
#d = (x*3)
#e = (x*4)
#f = (x*5)
#g = (x*6)
#h = (x*7)
#i = (x*8)
#j = (x*9)
#k = (x*10)
#print('{}x1={}'.format(x,b))
#print('{}x2={}'.format(x,c))
#print('{}x3={}'.format(x,d))
#print('{}x4={}'.format(x,e))
#print('{}x5={}'.format(x,f))
#print('{}x6={}'.format(x,g))
#print('{}x7={}'.format(x,h))
#print('{}x8={}'.format(x,i))
#print('{}x9={}'.format(x,j))
#print('{}x10={}'.format(x,k))
#print('Prontinho, só estudar bem para saber tudo!')
### Outro jeito de fazer #####
num = int(input('De qual numero você quer saber a tabuada?'))
print('-'*12)
print('{} x {:2} = {}'.format(num, 1, (num*1)))
print('{} x {:2} = {}'.format(num, 2, (num*2)))
print('{} x {:2} = {}'.format(num, 3, (num*3)))
print('{} x {:2} = {}'.format(num, 4, (num*4)))
print('{} x {:2} = {}'.format(num, 5, (num*5)))
print('{} x {:2} = {}'.format(num, 6, (num*6)))
print('{} x {:2} = {}'.format(num, 7, (num*7)))
print('{} x {:2} = {}'.format(num, 8, (num*8)))
print('{} x {:2} = {}'.format(num, 9, (num*9)))
print('{} x {:2} = {}'.format(num, 10, (num*10)))
print('-'*12)