a = float(input('Digite aqui o número em metro para conversão:'))
km = (a/1000)
hm = (a/100)
dam = (a/10)
dm = (a*10)
cm: float = (a*100)
mm = (a*1000)
print('O valor em quilômetros é {}km'.format(km))
print('O valor em hectômetro é {}hm'.format(hm))
print('O valor em decâmetros é {}dam'.format(dam))
print('O valor em quilômetros é {}km'.format(km))
print('Valor em centímetro {:.0f}cm.\nValor em milímetros {:.0f}mm.\n'.format(cm, mm))
